@admin_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhNDcwMzU4NS00NTcxLTQzZTctYjAzOC0zNWE3YzRmY2M2YWEiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTEwOTI5NDUsImV4cCI6MTc1MTY5Nzc0NX0.yps1trJMZWpOiB36nbM5I4Gy1_p1Wk1EKxhxQxym1-0
@agent_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZTc5ODQwOS01MDQ2LTQxODgtODgyOC01ODU5OTZkNDNkOWIiLCJyb2xlIjoiQUdFTlQiLCJpYXQiOjE3NTEwOTMwNDQsImV4cCI6MTc1MTY5Nzg0NH0.t2SAoN6iOFXeN96DF3zGPN1XyQ8eQVzoEO5IwqMaICc

### Create Vehicle Category
POST http://localhost:3000/vehicle-categories
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "name": "SUV",
  "description": "Sport Utility Vehicle"
}

### Get All Categories
GET http://localhost:3000/vehicle-categories
Authorization: Bearer {{admin_token}}

### Update Vehicle Category
PATCH http://localhost:3000/vehicle-categories/:id
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "description": "Updated description"
}

### Delete Vehicle Category
DELETE http://localhost:3000/vehicle-categories/ccd0e18f-9475-48da-b087-4a578fc114e1
Authorization: Bearer {{admin_token}}
